"""Continuous-pose kinematics.

The polygon-sim primary state is body-frame. Each plate carries a
continuous world-frame pose (``position_km``, ``orientation_rad``) that
gets incremented per tick by ``velocity_kmpy * dt`` and
``angular_velocity_rad_per_myr * dt``. The body-frame paint arrays
DO NOT MOVE — only the pose changes. World-frame views are
regenerated by :func:`tectonic_sim.polygon_sim.rasterize.rasterise`.

This replaces the previous architecture's per-tick ``np.roll``
translation and NN/bilinear inverse-resample rotation, both of which
introduced grid aliasing that made small rotations invisible and
forced ``_trailing_edge_fill`` to plug rotation-vacated cells.
"""

from __future__ import annotations

import numpy as np

from tectonic_sim.types import WorldRect

from tectonic_sim.polygon_sim.types import PolygonPlate


def _advance_pose(
    plates: list[PolygonPlate], dt: float, domain: WorldRect,
) -> None:
    """Advance each plate's continuous pose by one tick.

    Translation: ``position_km += velocity_kmpy * dt``, wrapped to the
    torus so the position stays in the centred ``[-half, +half]`` range.
    Rotation: ``orientation_rad += angular_velocity_rad_per_myr * dt``.
    """
    half_w = domain.half_width_km
    half_h = domain.half_height_km
    for p in plates:
        if not p.alive:
            continue
        p.position_km = p.position_km + p.velocity_kmpy * dt
        # Wrap into the centred torus.
        p.position_km[0] = (
            (p.position_km[0] + half_w) % domain.width_km - half_w
        )
        p.position_km[1] = (
            (p.position_km[1] + half_h) % domain.height_km - half_h
        )
        p.orientation_rad = float(
            p.orientation_rad + p.angular_velocity_rad_per_myr * dt
        )
